### ISSUE TITLE
Some songs are not fully annotated, or mismatched?

### ISSUE THREAD

**Issue by zhanh-he** [fosfrancesco/asap-dataset#4]
Hi, I found that some songs haven't been fully annotated, most notably the beats in the "txt" file. Just wondering it is partially annotated, or the annotation is wrongly matched the song. Here is the list:
1. Beethoven/Piano/Sonatas/11-1/MaximovI02M.wav: total 1326s, annotation stop at 312.4s (beats, downbeats, key sign, ...).
2. Beethoven/Piano/Sonatas/9-1/Tysman05M.wav: total 434s, annotation stop at 264s.

Great appriciate your great works! The source dataset I used is maestro v2.0 and git was replicated on 01 Feb 2023, both matching the description of the ASAP dataset.

Best, Zhanh

**Comment by apmcleod** [comment]
Hello Zhanh,

Thank you for raising the issue. We will have a look at it shortly.

**Comment by fosfrancesco** [comment]
Hello Zhanh, good catch! This is indeed a problem in the dataset. The MIDI and audio performances are clearly containing some part that is not on the score.
We will release an update of ASAP the next month that corrects such problems. 

However, from a fast visual evaluation, it seems that the existing annotations are correct. So if you still want to use these files, meanwhile you can manually cut the audio (and MIDI if you are using it).
- For Beethoven/Piano/Sonatas/11-1/MaximovI02M.wav around 5.20 minutes
- For Beethoven/Piano/Sonatas/9-1/Tysman05M.wav around 4.28 minutes
All annotations will still be correct.

Also, you can use the branch `corrections2` where we already corrected some other problems we found along the way.

Thank you for your contribution!
